(defun make-pairs (row to-row col to-col)
  (let ((form "std::make_pair(%d, %d),")
	(r row) (c col) (output ""))
    (while (< r to-row)
      (while (< c to-col)
	(setf output (concat output (format form r c)))
	(setf c (1+ c)))
      (setf output (concat output "\n"))
      (setf c col)
      (setf r (1+ r)))
    output))
